<?php
    require_once "./clases/alumno.php";
    require_once "./clases/profesor.php";
    require_once "./clases/aula.php";
    require_once "./clases/instituto.php";
    require_once "./clases/persona.php";

    $alu1 = new Alumno("Marina", "Meza", "F", 102315);
    $alu2 = new Alumno("Gabriel", "Mendoza", "M", 102314);
    $alu3 = new Alumno("Pepe", "Mito", "M", 120315);
    $alu4 = new Alumno("María", "Gonzalez", "M", 120542);
    $alu5 = new Alumno("José", "Piero", "M", 102345);
    $alu6 = new Alumno("Juan", "Tito", "M", 102254);
    $alu7 = new Alumno("Mariana", "López", "F", 102154);
    $alu8 = new Alumno("Belén", "Ruiz", "F", 102251);
    $alu9 = new Alumno("Juan Pablo", "Gómez", "M", 102252);
    $alu10 = new Alumno("Maria", "La del barrio", "F", 103546);
    $pro1 = new Profesor("Octavio", "Villegas", "M", 102101);
    $pro2 = new Profesor("Mario", "Rampi", "M", 102102);
    $pro3 = new Profesor("Yanina", "López", "F", 102154);
    $pro4 = new Profesor("Maximiliano", "Neiner", "M", 102145);
    $pro5 = new Profesor("Enrique", "Prats", "M", 102531);
    $pro6 = new Profesor("Pepe", "Piero", "M", 120153);
    $aul1 = new Aula("1ºA", $pro3);
    $aul2 = new Aula("1ºB", $pro3);
    $aul3 = new Aula("1ºC", $pro2);
    $aul4 = new Aula("1ºD", $pro2);
    $aul5 = new Aula("2ºA", $pro1);
    $aul6 = new Aula("2ºB", $pro4);
    $aul7 = new Aula("3ºA", $pro2);
    $aul8 = new Aula("3ºB", $pro5);
    $aul9 = new Aula("4ºA", $pro1);
    $aul10 = new Aula("4ºB", $pro4);
    $aul11 = new Aula("5ºA", $pro6);
    $aul1->CargarAlumno($alu1);
    $aul1->CargarAlumno($alu2);
    $aul2->CargarAlumno($alu2);
    $aul2->CargarAlumno($alu4);
    $aul2->CargarAlumno($alu6);
    $aul2->CargarAlumno($alu8);
    $aul3->CargarAlumno($alu8);
    $aul3->CargarAlumno($alu9);
    $aul4->CargarAlumno($alu1);
    $aul4->CargarAlumno($alu2);
    $aul4->CargarAlumno($alu3);
    $aul4->CargarAlumno($alu4);
    $aul5->CargarAlumno($alu7);
    $aul5->CargarAlumno($alu9);
    $aul5->CargarAlumno($alu10);
    $aul6->CargarAlumno($alu3);
    $aul6->CargarAlumno($alu5);
    $aul6->CargarAlumno($alu10);
    $aul7->CargarAlumno($alu1);
    $aul7->CargarAlumno($alu7);
    $aul7->CargarAlumno($alu8);
    $aul7->CargarAlumno($alu10);
    $aul8->CargarAlumno($alu2);
    $aul8->CargarAlumno($alu3);
    $aul8->CargarAlumno($alu4);
    $aul9->CargarAlumno($alu2);
    $aul9->CargarAlumno($alu3);
    $aul9->CargarAlumno($alu4);
    $aul9->CargarAlumno($alu5);
    $aul9->CargarAlumno($alu6);
    $aul9->CargarAlumno($alu9);
    $aul10->CargarAlumno($alu5);
    $aul10->CargarAlumno($alu8);
    $aul10->CargarAlumno($alu10);
    $aul11->CargarAlumno($alu3);
    $aul11->CargarAlumno($alu8);
    $ins1 = new Instituto("Los Pitagoricos");
    $ins1->CargarAula($aul1);
    $ins1->CargarAula($aul2);
    $ins1->CargarAula($aul3);
    $ins1->CargarAula($aul4);
    $ins1->CargarAula($aul5);
    $ins1->CargarAula($aul6);
    $ins1->CargarAula($aul7);
    $ins1->CargarAula($aul8);
    $ins1->CargarAula($aul9);
    $ins1->CargarAula($aul10);
    $ins1->CargarAula($aul11);

    /*echo $ins1->BuscarAlumnoPorAula("gómez");
    echo "<br/><br/>";
    echo $ins1->BuscarAlumnoPorLibreta(102153);
    echo "<br/><br/>";
    echo $ins1->BuscarProfesorPorLegajo(102145);*/
    //echo $ins1->CantidadAulasPorLibreta(102154);
    //echo $aul3->MostrarPersonas();
    echo $ins1->BuscarPersonaPorAula("meza");
?>